apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3app6-deployment
spec:
  selector:
    matchLabels:
      app: k3app6-pod
  template:
    metadata:
      labels:
        app: k3app6-pod
    spec:
      containers:
      - name: k3app6-container
        image: kiranacr.azurecr.io/k3app6:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
